---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    app: javaapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      - name: container1
        image: gcr.io/murthylab/java:v1
        volumeMounts:
        - mountPath: /mnt
          name: shared-volume
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet: 
            path : /hello
            port: 8080
          initialDelaySeconds: 50
          periodSeconds: 5
        livenessProbe:
          httpGet: 
            path : /hello
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        resources:
          requests:
            memory: "80Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      - name: container2
        image: gcr.io/murthylab/nginx:latest
        volumeMounts:
        - mountPath: /mnt
          name: pvc
        - mountPath: /tmp
          name: shared-volume
        ports:
        - containerPort: 8080    

      volumes:
      - name: shared-volume
        emptyDir: {}
      - name: pvc
        persistentVolumeClaim:
          claimName: pvc-vol
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: javaapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---